"""
Django settings for devzwebsite project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os, environ

env = environ.Env()
environ.Env.read_env()


STRIPE_SK_TEST_KEY = env("STRIPE_SK_TEST_KEY")
STRIPE_PK_TEST_KEY = env("STRIPE_PK_TEST_KEY")

# Or like that depending on how you use your environment variables:
# STRIPE_SK_TEST_KEY = str(os.getenv("STRIPE_SK_TEST_KEY"))
# STRIPE_PK_TEST_KEY = str(os.getenv("STRIPE_PK_TEST_KEY"))
